/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_raed_manage_coach (void);
GtkWidget* create_raed_reserve_materiel (void);
GtkWidget* create_yassinemanagemembres (void);
GtkWidget* create_yassinerequestcoach (void);
GtkWidget* create_yomna_choose_course (void);
GtkWidget* create_yomna_course_managment (void);
GtkWidget* create_windowadmin (void);
GtkWidget* create_login (void);
GtkWidget* create_windowtrainer (void);
GtkWidget* create_space_admin (void);
GtkWidget* create_space_coach (void);
GtkWidget* create_space_members (void);
