/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_raed_manage_coach (void)
{
  GtkWidget *raed_manage_coach;
  GtkWidget *fixed13;
  GtkWidget *treeviewmanage;
  GtkWidget *entry26;
  GtkWidget *entryname2;
  GtkWidget *entryfirstname;
  GtkWidget *label82;
  GtkWidget *entry29;
  GtkWidget *entryid;
  GtkWidget *entryphonenumber;
  GtkObject *spinbuttonday_adj;
  GtkWidget *spinbuttonday;
  GtkObject *spinbuttonmonth_adj;
  GtkWidget *spinbuttonmonth;
  GtkWidget *hseparator2;
  GtkWidget *entryname1;
  GtkWidget *label93;
  GtkWidget *label96;
  GtkObject *spinbuttonyear_adj;
  GtkWidget *spinbuttonyear;
  GtkWidget *label90;
  GtkWidget *label88;
  GtkWidget *btdelete;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label176;
  GtkWidget *btsearch;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label177;
  GtkWidget *checkbuttoncentre;
  GtkWidget *label94;
  GtkWidget *label95;
  GtkWidget *label98;
  GtkWidget *label99;
  GtkWidget *entrycentre1;
  GtkWidget *entrycentre2;
  GtkWidget *label85;
  GtkWidget *checkbuttonname;
  GtkWidget *label91;
  GtkWidget *label83;
  GtkWidget *label84;
  GtkWidget *label86;
  GtkWidget *label97;
  GtkWidget *label101;
  GtkWidget *hseparator5;
  GtkWidget *label92;
  GtkWidget *radiobuttonman;
  GSList *radiobuttonman_group = NULL;
  GtkWidget *radiobuttonwomen;
  GtkWidget *btadd;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label175;
  GtkWidget *btmodify;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label174;

  raed_manage_coach = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (raed_manage_coach), _("raed_manage_coach"));

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (raed_manage_coach), fixed13);
  gtk_widget_set_size_request (fixed13, 900, 700);

  treeviewmanage = gtk_tree_view_new ();
  gtk_widget_show (treeviewmanage);
  gtk_fixed_put (GTK_FIXED (fixed13), treeviewmanage, 48, 208);
  gtk_widget_set_size_request (treeviewmanage, 624, 160);

  entry26 = gtk_entry_new ();
  gtk_widget_show (entry26);
  gtk_fixed_put (GTK_FIXED (fixed13), entry26, 112, 440);
  gtk_widget_set_size_request (entry26, 120, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry26), 8226);

  entryname2 = gtk_entry_new ();
  gtk_widget_show (entryname2);
  gtk_fixed_put (GTK_FIXED (fixed13), entryname2, 112, 488);
  gtk_widget_set_size_request (entryname2, 120, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryname2), 8226);

  entryfirstname = gtk_entry_new ();
  gtk_widget_show (entryfirstname);
  gtk_fixed_put (GTK_FIXED (fixed13), entryfirstname, 112, 536);
  gtk_widget_set_size_request (entryfirstname, 120, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryfirstname), 8226);

  label82 = gtk_label_new (_("ID"));
  gtk_widget_show (label82);
  gtk_fixed_put (GTK_FIXED (fixed13), label82, 32, 432);
  gtk_widget_set_size_request (label82, 72, 32);

  entry29 = gtk_entry_new ();
  gtk_widget_show (entry29);
  gtk_fixed_put (GTK_FIXED (fixed13), entry29, 112, 440);
  gtk_widget_set_size_request (entry29, 120, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry29), 8226);

  entryid = gtk_entry_new ();
  gtk_widget_show (entryid);
  gtk_fixed_put (GTK_FIXED (fixed13), entryid, 112, 440);
  gtk_widget_set_size_request (entryid, 120, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryid), 8226);

  entryphonenumber = gtk_entry_new ();
  gtk_widget_show (entryphonenumber);
  gtk_fixed_put (GTK_FIXED (fixed13), entryphonenumber, 416, 488);
  gtk_widget_set_size_request (entryphonenumber, 128, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryphonenumber), 8226);

  spinbuttonday_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttonday = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonday_adj), 1, 0);
  gtk_widget_show (spinbuttonday);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbuttonday, 408, 440);
  gtk_widget_set_size_request (spinbuttonday, 60, 27);

  spinbuttonmonth_adj = gtk_adjustment_new (12, 1, 12, 1, 10, 10);
  spinbuttonmonth = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonmonth_adj), 1, 0);
  gtk_widget_show (spinbuttonmonth);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbuttonmonth, 480, 440);
  gtk_widget_set_size_request (spinbuttonmonth, 60, 27);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_show (hseparator2);
  gtk_fixed_put (GTK_FIXED (fixed13), hseparator2, 240, 400);
  gtk_widget_set_size_request (hseparator2, 400, 16);

  entryname1 = gtk_entry_new ();
  gtk_widget_show (entryname1);
  gtk_fixed_put (GTK_FIXED (fixed13), entryname1, 104, 136);
  gtk_widget_set_size_request (entryname1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryname1), 8226);

  label93 = gtk_label_new (_("centre"));
  gtk_widget_show (label93);
  gtk_fixed_put (GTK_FIXED (fixed13), label93, 288, 144);
  gtk_widget_set_size_request (label93, 72, 16);

  label96 = gtk_label_new (_("Date of birth "));
  gtk_widget_show (label96);
  gtk_fixed_put (GTK_FIXED (fixed13), label96, 272, 448);
  gtk_widget_set_size_request (label96, 112, 16);

  spinbuttonyear_adj = gtk_adjustment_new (2000, 1900, 9999, 1, 1, 10);
  spinbuttonyear = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonyear_adj), 1, 0);
  gtk_widget_show (spinbuttonyear);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbuttonyear, 552, 440);
  gtk_widget_set_size_request (spinbuttonyear, 80, 24);

  label90 = gtk_label_new (_("MANAGE Coaches"));
  gtk_widget_show (label90);
  gtk_fixed_put (GTK_FIXED (fixed13), label90, 0, 200);
  gtk_widget_set_size_request (label90, 432, 96);
  gtk_misc_set_alignment (GTK_MISC (label90), 0.44, 0.5);

  label88 = gtk_label_new (_("ACTION ON Coaches "));
  gtk_widget_show (label88);
  gtk_fixed_put (GTK_FIXED (fixed13), label88, 0, 384);
  gtk_widget_set_size_request (label88, 272, 48);

  btdelete = gtk_button_new ();
  gtk_widget_show (btdelete);
  gtk_fixed_put (GTK_FIXED (fixed13), btdelete, 688, 272);
  gtk_widget_set_size_request (btdelete, 112, 32);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (btdelete), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label176 = gtk_label_new_with_mnemonic (_("DELETE"));
  gtk_widget_show (label176);
  gtk_box_pack_start (GTK_BOX (hbox8), label176, FALSE, FALSE, 0);

  btsearch = gtk_button_new ();
  gtk_widget_show (btsearch);
  gtk_fixed_put (GTK_FIXED (fixed13), btsearch, 688, 128);
  gtk_widget_set_size_request (btsearch, 104, 32);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (btsearch), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label177 = gtk_label_new_with_mnemonic (_("SEARCH"));
  gtk_widget_show (label177);
  gtk_box_pack_start (GTK_BOX (hbox9), label177, FALSE, FALSE, 0);

  checkbuttoncentre = gtk_check_button_new_with_mnemonic (_("Centre"));
  gtk_widget_show (checkbuttoncentre);
  gtk_fixed_put (GTK_FIXED (fixed13), checkbuttoncentre, 536, 152);
  gtk_widget_set_size_request (checkbuttoncentre, 118, 24);

  label94 = gtk_label_new (_(";;;"));
  gtk_widget_show (label94);
  gtk_fixed_put (GTK_FIXED (fixed13), label94, 808, 136);
  gtk_widget_set_size_request (label94, 49, 17);

  label95 = gtk_label_new (_(";;;"));
  gtk_widget_show (label95);
  gtk_fixed_put (GTK_FIXED (fixed13), label95, 816, 280);
  gtk_widget_set_size_request (label95, 49, 17);

  label98 = gtk_label_new (_(";;;"));
  gtk_widget_show (label98);
  gtk_fixed_put (GTK_FIXED (fixed13), label98, 720, 536);
  gtk_widget_set_size_request (label98, 49, 17);

  label99 = gtk_label_new (_(";;;"));
  gtk_widget_show (label99);
  gtk_fixed_put (GTK_FIXED (fixed13), label99, 720, 640);
  gtk_widget_set_size_request (label99, 49, 17);

  entrycentre1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (entrycentre1);
  gtk_fixed_put (GTK_FIXED (fixed13), entrycentre1, 368, 136);
  gtk_widget_set_size_request (entrycentre1, 93, 24);
  gtk_combo_box_append_text (GTK_COMBO_BOX (entrycentre1), _("Tunis \t"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entrycentre1), _("Ariana "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entrycentre1), _("Manouba "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entrycentre1), _("Ben arous "));

  entrycentre2 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (entrycentre2);
  gtk_fixed_put (GTK_FIXED (fixed13), entrycentre2, 112, 584);
  gtk_widget_set_size_request (entrycentre2, 125, 24);
  gtk_combo_box_append_text (GTK_COMBO_BOX (entrycentre2), _("Tunis \t"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entrycentre2), _("Ariana "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entrycentre2), _("Manouba "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entrycentre2), _("Ben arous "));

  label85 = gtk_label_new (_("Phone Number"));
  gtk_widget_show (label85);
  gtk_fixed_put (GTK_FIXED (fixed13), label85, 288, 488);
  gtk_widget_set_size_request (label85, 104, 24);

  checkbuttonname = gtk_check_button_new_with_mnemonic (_("Name"));
  gtk_widget_show (checkbuttonname);
  gtk_fixed_put (GTK_FIXED (fixed13), checkbuttonname, 536, 120);
  gtk_widget_set_size_request (checkbuttonname, 118, 24);

  label91 = gtk_label_new (_("Name"));
  gtk_widget_show (label91);
  gtk_fixed_put (GTK_FIXED (fixed13), label91, 40, 144);
  gtk_widget_set_size_request (label91, 49, 17);

  label83 = gtk_label_new (_("Name"));
  gtk_widget_show (label83);
  gtk_fixed_put (GTK_FIXED (fixed13), label83, 32, 480);
  gtk_widget_set_size_request (label83, 72, 32);

  label84 = gtk_label_new (_("First name"));
  gtk_widget_show (label84);
  gtk_fixed_put (GTK_FIXED (fixed13), label84, 32, 536);
  gtk_widget_set_size_request (label84, 72, 32);

  label86 = gtk_label_new (_("Gender "));
  gtk_widget_show (label86);
  gtk_fixed_put (GTK_FIXED (fixed13), label86, 288, 528);
  gtk_widget_set_size_request (label86, 72, 24);

  label97 = gtk_label_new (_("Centre"));
  gtk_widget_show (label97);
  gtk_fixed_put (GTK_FIXED (fixed13), label97, 40, 592);
  gtk_widget_set_size_request (label97, 49, 17);

  label101 = gtk_label_new (_("Manage Coaches"));
  gtk_widget_show (label101);
  gtk_fixed_put (GTK_FIXED (fixed13), label101, 304, 32);
  gtk_widget_set_size_request (label101, 272, 40);

  hseparator5 = gtk_hseparator_new ();
  gtk_widget_show (hseparator5);
  gtk_fixed_put (GTK_FIXED (fixed13), hseparator5, 216, 96);
  gtk_widget_set_size_request (hseparator5, 352, 16);

  label92 = gtk_label_new (_("search for a Coach by  "));
  gtk_widget_show (label92);
  gtk_fixed_put (GTK_FIXED (fixed13), label92, 0, 80);
  gtk_widget_set_size_request (label92, 248, 48);

  radiobuttonman = gtk_radio_button_new_with_mnemonic (NULL, _("Man"));
  gtk_widget_show (radiobuttonman);
  gtk_fixed_put (GTK_FIXED (fixed13), radiobuttonman, 384, 528);
  gtk_widget_set_size_request (radiobuttonman, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonman), radiobuttonman_group);
  radiobuttonman_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonman));

  radiobuttonwomen = gtk_radio_button_new_with_mnemonic (NULL, _("Women"));
  gtk_widget_show (radiobuttonwomen);
  gtk_fixed_put (GTK_FIXED (fixed13), radiobuttonwomen, 472, 528);
  gtk_widget_set_size_request (radiobuttonwomen, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonwomen), radiobuttonman_group);
  radiobuttonman_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonwomen));

  btadd = gtk_button_new ();
  gtk_widget_show (btadd);
  gtk_fixed_put (GTK_FIXED (fixed13), btadd, 688, 496);
  gtk_widget_set_size_request (btadd, 112, 32);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (btadd), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label175 = gtk_label_new_with_mnemonic (_("ADD"));
  gtk_widget_show (label175);
  gtk_box_pack_start (GTK_BOX (hbox7), label175, FALSE, FALSE, 0);

  btmodify = gtk_button_new ();
  gtk_widget_show (btmodify);
  gtk_fixed_put (GTK_FIXED (fixed13), btmodify, 688, 600);
  gtk_widget_set_size_request (btmodify, 112, 32);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (btmodify), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label174 = gtk_label_new_with_mnemonic (_("MODIFY"));
  gtk_widget_show (label174);
  gtk_box_pack_start (GTK_BOX (hbox6), label174, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) radiobuttonman, "toggled",
                    G_CALLBACK (on_radiobuttonman_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonwomen, "toggled",
                    G_CALLBACK (on_radiobuttonwomen_toggled),
                    NULL);
  g_signal_connect ((gpointer) btadd, "clicked",
                    G_CALLBACK (on_btadd_clicked),
                    NULL);
  g_signal_connect ((gpointer) btmodify, "clicked",
                    G_CALLBACK (on_btmodify_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (raed_manage_coach, raed_manage_coach, "raed_manage_coach");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, treeviewmanage, "treeviewmanage");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, entry26, "entry26");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, entryname2, "entryname2");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, entryfirstname, "entryfirstname");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, label82, "label82");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, entry29, "entry29");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, entryid, "entryid");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, entryphonenumber, "entryphonenumber");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, spinbuttonday, "spinbuttonday");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, spinbuttonmonth, "spinbuttonmonth");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, hseparator2, "hseparator2");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, entryname1, "entryname1");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, label93, "label93");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, label96, "label96");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, spinbuttonyear, "spinbuttonyear");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, label90, "label90");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, label88, "label88");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, btdelete, "btdelete");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, image8, "image8");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, label176, "label176");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, btsearch, "btsearch");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, image9, "image9");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, label177, "label177");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, checkbuttoncentre, "checkbuttoncentre");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, label94, "label94");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, label95, "label95");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, label98, "label98");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, label99, "label99");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, entrycentre1, "entrycentre1");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, entrycentre2, "entrycentre2");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, label85, "label85");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, checkbuttonname, "checkbuttonname");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, label91, "label91");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, label83, "label83");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, label84, "label84");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, label86, "label86");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, label97, "label97");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, label101, "label101");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, hseparator5, "hseparator5");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, label92, "label92");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, radiobuttonman, "radiobuttonman");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, radiobuttonwomen, "radiobuttonwomen");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, btadd, "btadd");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, image7, "image7");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, label175, "label175");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, btmodify, "btmodify");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, image6, "image6");
  GLADE_HOOKUP_OBJECT (raed_manage_coach, label174, "label174");

  return raed_manage_coach;
}

GtkWidget*
create_raed_reserve_materiel (void)
{
  GtkWidget *raed_reserve_materiel;
  GtkWidget *fixed19;
  GtkWidget *label197;
  GtkWidget *entryid;
  GtkWidget *entryname;
  GtkWidget *entryphonenumber;
  GtkObject *spinbuttonday_adj;
  GtkWidget *spinbuttonday;
  GtkObject *spinbuttonmonth_adj;
  GtkWidget *spinbuttonmonth;
  GtkObject *spinbuttonyear_adj;
  GtkWidget *spinbuttonyear;
  GtkWidget *treeview13;
  GtkWidget *label199;
  GtkWidget *label200;
  GtkWidget *hseparator13;
  GtkWidget *label198;
  GtkWidget *label202;
  GtkWidget *button39;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image22;
  GtkWidget *label203;
  GtkWidget *label201;
  GtkWidget *treeview14;
  GtkWidget *label204;
  GtkWidget *label205;
  GtkWidget *hseparator14;
  GtkWidget *btreserve_;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *image23;
  GtkWidget *label206;
  GtkWidget *label207;

  raed_reserve_materiel = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (raed_reserve_materiel, 900, 700);
  gtk_window_set_title (GTK_WINDOW (raed_reserve_materiel), _("raed_reserve_materiel"));

  fixed19 = gtk_fixed_new ();
  gtk_widget_show (fixed19);
  gtk_container_add (GTK_CONTAINER (raed_reserve_materiel), fixed19);
  gtk_widget_set_size_request (fixed19, 900, 700);

  label197 = gtk_label_new (_("Hello\n "));
  gtk_widget_show (label197);
  gtk_fixed_put (GTK_FIXED (fixed19), label197, 296, 48);
  gtk_widget_set_size_request (label197, 304, 40);

  entryid = gtk_entry_new ();
  gtk_widget_show (entryid);
  gtk_fixed_put (GTK_FIXED (fixed19), entryid, 144, 168);
  gtk_widget_set_size_request (entryid, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryid), 8226);

  entryname = gtk_entry_new ();
  gtk_widget_show (entryname);
  gtk_fixed_put (GTK_FIXED (fixed19), entryname, 144, 240);
  gtk_widget_set_size_request (entryname, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryname), 8226);

  entryphonenumber = gtk_entry_new ();
  gtk_widget_show (entryphonenumber);
  gtk_fixed_put (GTK_FIXED (fixed19), entryphonenumber, 144, 328);
  gtk_widget_set_size_request (entryphonenumber, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryphonenumber), 8226);

  spinbuttonday_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  spinbuttonday = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonday_adj), 1, 0);
  gtk_widget_show (spinbuttonday);
  gtk_fixed_put (GTK_FIXED (fixed19), spinbuttonday, 152, 408);
  gtk_widget_set_size_request (spinbuttonday, 60, 27);

  spinbuttonmonth_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbuttonmonth = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonmonth_adj), 1, 0);
  gtk_widget_show (spinbuttonmonth);
  gtk_fixed_put (GTK_FIXED (fixed19), spinbuttonmonth, 224, 408);
  gtk_widget_set_size_request (spinbuttonmonth, 60, 27);

  spinbuttonyear_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbuttonyear = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonyear_adj), 1, 0);
  gtk_widget_show (spinbuttonyear);
  gtk_fixed_put (GTK_FIXED (fixed19), spinbuttonyear, 296, 408);
  gtk_widget_set_size_request (spinbuttonyear, 60, 27);

  treeview13 = gtk_tree_view_new ();
  gtk_widget_show (treeview13);
  gtk_fixed_put (GTK_FIXED (fixed19), treeview13, 440, 152);
  gtk_widget_set_size_request (treeview13, 424, 200);

  label199 = gtk_label_new (_("Name "));
  gtk_widget_show (label199);
  gtk_fixed_put (GTK_FIXED (fixed19), label199, 72, 248);
  gtk_widget_set_size_request (label199, 57, 17);

  label200 = gtk_label_new (_("Phone Number "));
  gtk_widget_show (label200);
  gtk_fixed_put (GTK_FIXED (fixed19), label200, 40, 328);
  gtk_widget_set_size_request (label200, 104, 24);

  hseparator13 = gtk_hseparator_new ();
  gtk_widget_show (hseparator13);
  gtk_fixed_put (GTK_FIXED (fixed19), hseparator13, 288, 112);
  gtk_widget_set_size_request (hseparator13, 448, 24);

  label198 = gtk_label_new (_("ID"));
  gtk_widget_show (label198);
  gtk_fixed_put (GTK_FIXED (fixed19), label198, 64, 168);
  gtk_widget_set_size_request (label198, 80, 24);

  label202 = gtk_label_new (_("Date of birth "));
  gtk_widget_show (label202);
  gtk_fixed_put (GTK_FIXED (fixed19), label202, 32, 408);
  gtk_widget_set_size_request (label202, 104, 24);

  button39 = gtk_button_new ();
  gtk_widget_show (button39);
  gtk_fixed_put (GTK_FIXED (fixed19), button39, 456, 392);
  gtk_widget_set_size_request (button39, 128, 40);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (button39), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image22 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox22), image22, FALSE, FALSE, 0);

  label203 = gtk_label_new_with_mnemonic (_("choose "));
  gtk_widget_show (label203);
  gtk_box_pack_start (GTK_BOX (hbox22), label203, FALSE, FALSE, 0);

  label201 = gtk_label_new (_(";;;"));
  gtk_widget_show (label201);
  gtk_fixed_put (GTK_FIXED (fixed19), label201, 592, 384);
  gtk_widget_set_size_request (label201, 232, 48);

  treeview14 = gtk_tree_view_new ();
  gtk_widget_show (treeview14);
  gtk_fixed_put (GTK_FIXED (fixed19), treeview14, 448, 488);
  gtk_widget_set_size_request (treeview14, 432, 200);

  label204 = gtk_label_new (_("Choose Course "));
  gtk_widget_show (label204);
  gtk_fixed_put (GTK_FIXED (fixed19), label204, 0, 80);
  gtk_widget_set_size_request (label204, 408, 80);

  label205 = gtk_label_new (_("Reserve Material"));
  gtk_widget_show (label205);
  gtk_fixed_put (GTK_FIXED (fixed19), label205, 24, 472);
  gtk_widget_set_size_request (label205, 168, 16);

  hseparator14 = gtk_hseparator_new ();
  gtk_widget_show (hseparator14);
  gtk_fixed_put (GTK_FIXED (fixed19), hseparator14, 208, 472);
  gtk_widget_set_size_request (hseparator14, 496, 16);

  btreserve_ = gtk_button_new ();
  gtk_widget_show (btreserve_);
  gtk_fixed_put (GTK_FIXED (fixed19), btreserve_, 200, 592);
  gtk_widget_set_size_request (btreserve_, 144, 40);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (btreserve_), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  image23 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox23), image23, FALSE, FALSE, 0);

  label206 = gtk_label_new_with_mnemonic (_("Reserve"));
  gtk_widget_show (label206);
  gtk_box_pack_start (GTK_BOX (hbox23), label206, FALSE, FALSE, 0);

  label207 = gtk_label_new (_(";;;"));
  gtk_widget_show (label207);
  gtk_fixed_put (GTK_FIXED (fixed19), label207, 248, 656);
  gtk_widget_set_size_request (label207, 57, 17);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (raed_reserve_materiel, raed_reserve_materiel, "raed_reserve_materiel");
  GLADE_HOOKUP_OBJECT (raed_reserve_materiel, fixed19, "fixed19");
  GLADE_HOOKUP_OBJECT (raed_reserve_materiel, label197, "label197");
  GLADE_HOOKUP_OBJECT (raed_reserve_materiel, entryid, "entryid");
  GLADE_HOOKUP_OBJECT (raed_reserve_materiel, entryname, "entryname");
  GLADE_HOOKUP_OBJECT (raed_reserve_materiel, entryphonenumber, "entryphonenumber");
  GLADE_HOOKUP_OBJECT (raed_reserve_materiel, spinbuttonday, "spinbuttonday");
  GLADE_HOOKUP_OBJECT (raed_reserve_materiel, spinbuttonmonth, "spinbuttonmonth");
  GLADE_HOOKUP_OBJECT (raed_reserve_materiel, spinbuttonyear, "spinbuttonyear");
  GLADE_HOOKUP_OBJECT (raed_reserve_materiel, treeview13, "treeview13");
  GLADE_HOOKUP_OBJECT (raed_reserve_materiel, label199, "label199");
  GLADE_HOOKUP_OBJECT (raed_reserve_materiel, label200, "label200");
  GLADE_HOOKUP_OBJECT (raed_reserve_materiel, hseparator13, "hseparator13");
  GLADE_HOOKUP_OBJECT (raed_reserve_materiel, label198, "label198");
  GLADE_HOOKUP_OBJECT (raed_reserve_materiel, label202, "label202");
  GLADE_HOOKUP_OBJECT (raed_reserve_materiel, button39, "button39");
  GLADE_HOOKUP_OBJECT (raed_reserve_materiel, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (raed_reserve_materiel, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (raed_reserve_materiel, image22, "image22");
  GLADE_HOOKUP_OBJECT (raed_reserve_materiel, label203, "label203");
  GLADE_HOOKUP_OBJECT (raed_reserve_materiel, label201, "label201");
  GLADE_HOOKUP_OBJECT (raed_reserve_materiel, treeview14, "treeview14");
  GLADE_HOOKUP_OBJECT (raed_reserve_materiel, label204, "label204");
  GLADE_HOOKUP_OBJECT (raed_reserve_materiel, label205, "label205");
  GLADE_HOOKUP_OBJECT (raed_reserve_materiel, hseparator14, "hseparator14");
  GLADE_HOOKUP_OBJECT (raed_reserve_materiel, btreserve_, "btreserve_");
  GLADE_HOOKUP_OBJECT (raed_reserve_materiel, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (raed_reserve_materiel, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (raed_reserve_materiel, image23, "image23");
  GLADE_HOOKUP_OBJECT (raed_reserve_materiel, label206, "label206");
  GLADE_HOOKUP_OBJECT (raed_reserve_materiel, label207, "label207");

  return raed_reserve_materiel;
}

