/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *raed_manage_coach;
  GtkWidget *raed_reserve_materiel;
  GtkWidget *windowadmin;
  GtkWidget *login;
  GtkWidget *windowtrainer;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * Open ALL windows for testing
   */
  
  // 1. Coach Management Window
  raed_manage_coach = create_raed_manage_coach();
  gtk_widget_show(raed_manage_coach);
  
  // 2. Equipment Reservation Window
  raed_reserve_materiel = create_raed_reserve_materiel();
  gtk_widget_show(raed_reserve_materiel);
  
  // 3. Admin Window
  windowadmin = create_windowadmin();
  gtk_widget_show(windowadmin);
  
  // 4. Login Window
  login = create_login();
  gtk_widget_show(login);
  
  // 5. Trainer Window
  windowtrainer = create_windowtrainer();
  gtk_widget_show(windowtrainer);

  /*
   * If you have the commented-out windows (from interface.c),
   * you can uncomment and add them too:
   */
  /*
  // Uncomment these if you want to test all windows:
  
  // Member Management Window
  GtkWidget *yassinemanagemembres = create_yassinemanagemembres();
  gtk_widget_show(yassinemanagemembres);
  
  // Request Coach Window
  GtkWidget *yassinerequestcoach = create_yassinerequestcoach();
  gtk_widget_show(yassinerequestcoach);
  
  // Choose Course Window
  GtkWidget *yomna_choose_course = create_yomna_choose_course();
  gtk_widget_show(yomna_choose_course);
  
  // Course Management Window
  GtkWidget *yomna_course_managment = create_yomna_course_managment();
  gtk_widget_show(yomna_course_managment);
  
  // Space Admin Window
  GtkWidget *space_admin = create_space_admin();
  gtk_widget_show(space_admin);
  
  // Space Coach Window
  GtkWidget *space_coach = create_space_coach();
  gtk_widget_show(space_coach);
  
  // Space Members Window
  GtkWidget *space_members = create_space_members();
  gtk_widget_show(space_members);
  */

  gtk_main();
  return 0;
}
